import { requirePaidFeature, requireTrip } from "@/lib/access";
import {
  DEFAULT_PACKET_SECTIONS,
  loadTripPacket,
  PACKET_SECTIONS,
  type PacketSectionKey,
} from "@/lib/print-data";
import { PacketSection } from "@/components/print/sections";
import { PrintHeader } from "@/components/print/print-header";

export const dynamic = "force-dynamic";
export const metadata = { title: "Trip packet" };

export default async function TripPacketPrintPage({
  params,
  searchParams,
}: {
  params: Promise<{ tripId: string }>;
  searchParams: Promise<{ sections?: string }>;
}) {
  const { tripId } = await params;
  const { sections: raw } = await searchParams;
  const ctx = await requireTrip(tripId);
  requirePaidFeature(ctx, "trip-packet", `/orgs/${ctx.organization.slug}/trips/${tripId}`);

  const valid = new Set(PACKET_SECTIONS.map((s) => s.key as string));
  const requested = raw
    ?.split(",")
    .map((s) => s.trim())
    .filter((s) => valid.has(s)) as PacketSectionKey[] | undefined;

  // Keep the canonical section order regardless of how they arrive in the URL.
  const selected = (requested && requested.length > 0 ? requested : DEFAULT_PACKET_SECTIONS).sort(
    (a, b) =>
      PACKET_SECTIONS.findIndex((s) => s.key === a) - PACKET_SECTIONS.findIndex((s) => s.key === b),
  );

  const data = await loadTripPacket(tripId);

  return (
    <>
      <PrintHeader
        title="Trip Packet"
        tripName={data.trip.name}
        organizationName={data.trip.organization.name}
        destination={data.trip.destination}
        startDate={data.trip.startDate}
        endDate={data.trip.endDate}
      />

      {selected.map((section, index) => (
        <div key={section} className={index > 0 && index % 2 === 0 ? "print-break" : ""}>
          <PacketSection data={data} section={section} />
        </div>
      ))}

      <footer className="mt-8 border-t border-line pt-3 text-xs text-navy-faint">
        Generated by Ready. Set. Amen. — keep the trip together. Printed copies of medical and
        emergency information should stay with a trip leader and be destroyed after the trip.
      </footer>
    </>
  );
}
